const website = {
    "headings": [{
        "title": "Pre-Marriage", "description": "These sections are meant to be followed in order. Don't move on to the next point unless you've looked through all the links in a given section.", "phases": [{
            "phase": "Phase One", "description": "Don't even think about it until you're past these steps", "subheadings": [{
                "subheading": "Prayer", "subheading_description": "If you can't commit a few minutes a day to God, then you're not ready to commit to another person for life.", "links": [
                    { "name": "Sweetness of Salah", "link": "https://www.youtube.com/playlist?list=PLT2-p8rVhA7yEYt7uysw1C8oOWW8SC03D", "description": "Might be worth your while understanding that thing you do 5 times a day" }
                ]
            },
            {
                "subheading": "Breaking Bad Habits", "subheading_description": "Destroy the habit before it destroys you and your marriage", "links": [{ "name": "Pornography Addiction", "link": "https://www.youtube.com/watch?v=5wOnBtjLcdQ", "description": "“What's this doing on this website?” Better question is, are you aware of how many Muslims are addicted to this stuff?" }, { "name": "Sex, Porn and Paradise", "link": "https://www.youtube.com/watch?v=6o6b8sTsYU4", "description": "Discussion on sexuality and ponography addiction in the Muslim community" }, { "name": "The Elephant in the Room", "link": "https://www.youtube.com/watch?v=T1ZjDfHD6vM", "description": "Realest, most explicit, talk on pornography ever." }, { "name": "Pornography Is What the End of the World Looks Like", "link": "http://www.truthdig.com/report/item/pornography_is_what_the_end_of_the_world_looks_like_20150215", "description": "Know thy enemy" }, { "name": "How to Overcome a Porn Addiction and Be Productive Again Part 1", "link": "http://productivemuslim.com/pornography-danger-part-1-interview-with-wael-ibrahim/", "description": "Interview with Wael Ibrahim Pt 1" }, { "name": "How to Overcome a Porn Addiction and Be Productive Again Part 2", "link": "https://goo.gl/o1PGmY", "description": "Interview with Wael Ibrahim Pt 2" }, { "name": "The Rationality of Islamic Sexual Ethics: Zina", "link": "http://muslimmatters.org/2015/06/11/the-rationality-of-islamic-sexual-ethics-zina/", "description": "The intellectual reason why you can't do it" }]
            }, {
                "subheading": "Repentance", "subheading_description": "(Seek) Forgive(ness) and Forget", "links": [{ "name": "Repent, Allah Loves You", "link": "https://www.youtube.com/watch?v=H-pSv9w32FY", "description": "Allah Loves you BECAUSE you keep repenting" }]
            }, {
                "subheading": "Instilling Good Habits", "subheading_description": "This will help you prep, and maintain chastity while you educate yourself on the subject", "links": [{ "name": "Self Development", "link": "https://www.youtube.com/watch?v=6UXWLIHFIjE", "description": "Help yourself before trying to help someone else" }, { "name": "Fiqh of Fasting in PDF form", "link": "/pdfs/Fiqh of Fasting.pdf", "description": "How to control your desires, but in PDF form - courtesy of Shaykh Mustafa Umar from California Islamic University" }]
            }]
        },
        {
            "phase": "Phase Two", "description": "Understand the Basics", "subheadings": [{
                "subheading": "Du'a", "subheading_description": "Want the best spouse for yourself? Ask the One who made that spouse for you", "links": [{ "name": "Du'a for a Righteous Spouse", "link": "http://youtube.com/watch?v=KqNfitp14vc", "description": "This needs to be recited, in like, every prayer you do" }, { "name": "Istikharah: How To and Why?", "link": "https://www.istikhara.com/", "description": "A site dedicated to teaching you how to make Istikhara" }]
            }, {

                "subheading": "What is Marriage?", "subheading_description": "Must be something worthwhile for us to create an entire website for it", "links": [{ "name": "The Status of Marriage in Islam", "link": "https://www.youtube.com/watch?v=EsmmQ2_wTvI", "description": "Spoiler Alert: It's important" }, { "name": "The Fiqh of Marriage", "link": "/pdfs/Fiqh of Marriage.pdf", "description": "PDF courtesy of Shaykh Mustafa Umar from California Islamic University" }, { "name": "Marriage Myths", "link": "https://www.youtube.com/watch?v=ITc_BQ5AEDc", "description": "Do you believe in these common myths about love and marriage?" }]
            }, {
                "subheading": "Know what you want", "subheading_description": "Most people don't even know what they're looking for in a spouse. Figure it out", "links": [{ "name": "How to Get Married: Know Yourself", "link": "https://www.youtube.com/watch?v=4-R57PGvUCM", "description": "Check yo-self before you wreck yo-self" }, { "name": "Pre-Marital Guide", "link": "https://static1.squarespace.com/static/592367dae3df281c9dca15ba/t/59ab3de4ff7c50083fcb7c8c/1504394725476/Noor.Premarital.Guide.pdf", "description": "Ask yourself the tough questions before you ask the other person" }, { "name": "Selection of a Prospective Spouse", "link": "https://youtube.com/watch?v=R-rD7egptVk", "description": "Long answer: this video. Short answer: Innie, mini, mynee, mo" }]
            }, {

                "subheading": "Interacting with the opposite gender", "subheading_description": "Don't pretend to be something you're not", "links": [{ "name": "Co-Ed Love for the Sake of Allah", "link": "http://www.virtualmosque.com/relationships/gender-relations/co-ed-love-for-the-sake-of-allah/", "description": "Your new go-to can be, \"I co-ed love her like a sister for the sake of Allah\"" }, { "name": "10 Guidelines for Gender Relations in Islam", "link": "http://www.virtualmosque.com/relationships/brotherhood-sisterhood/10-guidelines-for-gender-relations-in-islam/", "description": "This should be the charter of every Muslim Student Association" }, { "name": "Why Men and Women Can't Be Friends", "link": "https://www.youtube.com/watch?v=T_lh5fR4DMA", "description": "A facetious addition to the site — Because even the Non-Muslims understand the inherenet issue" }]
            }, {

                "subheading": "What to look for", "subheading_description": "The Prophet ﷺ gave us some awesome advice. It's a good idea to follow it", "links": [{ "name": "When You Marry for 4 Reasons, Don't Forget Your Reason", "link": "http://hadithoftheday.com/when-you-marry-for-four-reasons-dont-forget-your-reason/", "description": "Reason #5: You hate money" }, { "name": "How to Get Married: What to Look For", "link": "https://www.youtube.com/watch?v=2h97FkMA2PU", "description": "If only the actual search was as short as this video" }, { "name": "Search for the Soul Mate", "link": "https://www.youtube.com/watch?v=-K5LYCoDP3U", "description": "They should be from the South and specialize in making soul food" }, { "name": "Love & Marriage | Selecting Your Life Partner: Etiquette in Islam", "link": "https://www.youtube.com/watch?v=1znHn0x6D7w", "description": "Just try not to be awkward" }]
            }, {
                "subheading": "What is Love?", "subheading_description": "Finally, a definitive answer!", "links": [{ "name": "Does Love Exist Before Marriage", "link": "http://www.youtube.com/watch?v=IpIVSI5r0g8", "description": "Definitely. First person I ever said I love you too is Barney. And that was real love. Don't you tell me otherwise" }, { "name": "Is This Love I'm Feeling?", "link": "https://www.youtube.com/watch?v=seWk-G5LGdI", "description": "Depends on what you ate last night" }, { "name": "When Love it Not Enough", "link": "http://mentalhealth4muslims.com/when-love-is-not-enough-reassessing-marriage-in-the-muslim-community/", "description": "Reassessing Marriage In The Muslim Community" }, { "name": "Love Notes", "link": "https://youtube.com/watch?v=Pjv36MFP1vw", "description": "Shaykh Yasir Birjas dropping haqq right and left" }, { "name": "8 Misconceptions About Love", "link": "https://www.youtube.com/watch?v=Xg0eFlnCQBY", "description": "You know this is legit because he used a random number like eight, and didn't make things up to get to a round number like ten or something" }, { "name": "Romance in Islam", "link": "https://www.youtube.com/watch?v=cURZpC0CIqE", "description": "Just light a few musk-scented candles and bust out the Zamzam water" }]
            }]
        }, {
            "phase": "Phase Three", "description": "It Begins", "subheadings": [{

                "subheading": "Parents", "subheading_description": "Prepare yourself mentally for this.", "links": [{ "name": "How to Get Married: Talking to Your Parents", "link": "https://www.youtube.com/watch?v=V-g7kCC3Ss4", "description": "Make lots of dua. Like, A LOT a lot" }, { "name": "Bringing up the Conversation with the Parents", "link": "https://www.youtube.com/watch?v=tM6XHOU4z70&feature=youtu.be&t=47m48s", "description": "You'd think that it shouldn't be that hard, but then you'd be wrong" }, { "name": "Open the Doors to Marriage", "link": "https://youtube.com/watch?v=FXP39jFRfGY", "description": "And close the doors to haram" }]
            }, {
                "subheading": "The Proposal", "subheading_description": "Wanna be best fwends?", "links": [{ "name": "How to Get Married: Finding Someone", "link": "https://www.youtube.com/watch?v=Y-dyydXzU_I", "description": "Look in the right places" }, { "name": "How to Propose in 11 Easy Steps", "link": "https://muslimyouthmusings.com/11-tips-consider-proposing-marriage/", "description": "Oh, sure. \"Easy Steps,\" they say" }]
            }]
        }]
    }, {
        "title": "Getting Married", "description": "These sections are meant to be followed in order. Don't move on to the next point unless you've looked through all the links in a given section.", "phases": [{
            "phase": "Phase One", "description": "God be with you", "subheadings": [{

                "subheading": "Du'a", "subheading_description": "Yeah, same du'a. Amazing how these things work for multiple situations, right?", "links": [{ "name": "Du'a for a Righteous Spouse", "link": "http://youtube.com/watch?v=KqNfitp14vc", "description": "“But I already found a potential spouse!” Then make du'a that they're righteous" }, { "name": "Istikharah: How To and Why?", "link": "https://www.istikhara.com/", "description": "“But I already decided!” If you said that, then you really didn't understand the purpose of this prayer" }]
            }]
        }, {
            "phase": "Phase Two", "description": "Engaging Your Intended", "subheadings": [{
                "subheading": "Pre-Marriage Questions", "subheading_description": "“What's your favorite color?” is not one of the questions on the list", "links": [{ "name": "The Hidden Cost of Student Loans", "link": "https://web.archive.org/web/20190114155252/http://debtfreemuslims.com/story-hidden-costs-student-loans-one-told/", "description": "This is a Web Archive link. Might 404 on you :'(" }, { "name": "Pre-Marriage Questionnaire", "link": "pdfs/Pre-Marital Questionnaire.pdf", "description": "106 Questions to find out if they're the 1" }, { "name": "Marriage And Money", "link": "https://podcasts.apple.com/us/podcast/033-marriage-and-money-with-abdelrahman-murphy/id826787801?i=1000377253257", "description": "AbdelRahman Murphy teaching us about why knowing spending habits is a HUGE deal" }, { "name": "7 Things to Consider Before Saying I Do", "link": "https://www.youtube.com/watch?v=MezIB0zUUYo", "description": "Number 8 is whether or not they've gone through this site before " }, { "name": "M&M’s: Marriage and Money", "link": "http://www.virtualmosque.com/islam-studies/hot-topics/mms-marriage-and-money/", "description": "Ask for their credit score before you ask for their phone number. Haha jk jk... Unless...?" }, { "name": "How to do Basic Budgeting for Married Couples", "link": "https://youtube.com/watch?v=rsG_50u7EBY", "description": "Understand if you have enough to sustain another human being yet. " }]
            }, {
                "subheading": "Rights on Each Other", "subheading_description": "“Ask not what your spouse can do for you — ask what you can do for your spouse.” ", "links": [{ "name": "Wives and In-Laws", "link": "https://www.youtube.com/watch?v=Ziprwpl0AgE", "description": "You lose no matter which side you choose." }, { "name": "What are the Rights of the Wife", "link": "https://www.youtube.com/watch?v=C1XVLo9c8Tw", "description": "This is for the guy to memorize and for the girl to be aware of" }, { "name": "Guidance for Husbands", "link": "https://www.youtube.com/watch?v=U5h19uUTZTw", "description": "More guy stuff" }, { "name": "Responsibilities of Husbands and Responsibilities of Wives", "link": "https://www.youtube.com/watch?v=pbGir6-vUoU", "description": "Both sides got rights. But who's actually right?" }, { "name": "Muslim Women in Sacred Spaces", "link": "https://www.youtube.com/watch?v=kkVQHUZCqNU", "description": "Yes, they can go to the masjid. No, that 5x5 closet in the back of the prayer hall doesn't count" }, { "name": "Are you the Husband Allah Describes?", "link": "https://www.youtube.com/watch?v=qbA0zesP2ZQ", "description": "I assume you're not married yet when you read this, so the answer is no." }, { "name": "On Treating Women in Islam", "link": "https://www.youtube.com/watch?v=bFtZA8puDoM", "description": "Treat them right. Happy wife, happy life." }, { "name": "Obligations and Rights of the Muslimah", "link": "https://youtube.com/watch?v=n93ofHOFOQM", "description": "Turns out they have rights. Also turns out they don't always get them all." }]
            }, {
                "subheading": "Pitfalls of Marriage", "subheading_description": "Do you even know what you're about to get yourself into?", "links": [{ "name": "Muslim Marriage Crisis", "link": "https://youtube.com/watch?v=ZqXfHPIEXWM?t=27m23s", "description": "Understand the mistakes of the past so you don't repeat them" }, { "name": "Crisis of Marriage in America", "link": "https://youtube.com/watch?v=p14I7uFzpc4", "description": "So much crisis that we have two links to it" }]
            }, {
                "subheading": "Families Meeting and Culture Conflict", "subheading_description": "Good luck. Just kidding. Luck is shirk.", "links": [{ "name": "Thoughts and Advice on Interracial Marriage", "link": "https://muslimmatters.org/2007/04/06/thoughts-and-advice-on-interracial-marriages/", "description": "Br. Omar Usman with some much needed thoughts for those considering an interracial marriage" }, { "name": "Interracial Muslim Marriage", "link": "https://dawudwalid.wordpress.com/2016/01/25/advice-regarding-muslim-interracial-marriage-being-blocked/", "description": "Even more thoughts on Interracial Marriage" }, { "name": "Interracial Marriage in the Prophetic Era", "link": "https://www.almadina.org/studio/articles/interracial-marriage-in-the-prophetic-era", "description": "Racism isn't always why your family is against your choice in spouse" }, { "name": "How to Navigate the In-Law Relationship", "link": "https://www.qalaminstitute.org/2016/11/the-hangout-part-4-holidays-with-your-families-how-to-navigate-the-in-law-relationships/#.WDNsAbIrJhE", "description": "Shaykh Abdul Nasir Jangda and Ustadh Abdul Rahman Murphy on 'The Hangout' Podcast" }]
            }]
        }, {
            "phase": "Phase Three", "description": "The March to Victory", "subheadings": [{
                "subheading": "Engagement", "subheading_description": "Spoiler Alert: It doesn't change the boundaries", "links": [{ "name": "How to get Married: Engaged, What's Next", "link": "https://www.youtube.com/watch?v=FoGNO1V3X7Q", "description": "You can think about sending emojis without feeling guilty. But don't send any! You're not married yet!!" },]
            }, {
                "subheading": "Nikah", "subheading_description": "It's finally happening!", "links": [{ "name": "Example Nikah Contract", "link": "pdfs/Nikkah Contract Template.pdf", "description": "It's a legit contract you sign (or verbally agree to). There's no “kissing the bride” stuff here" }, { "name": "An Open Letter to Nervous Brides", "link": "http://aljumuah.com/an-open-letter-to-nervous-brides/", "description": "Last minute nerves are real" }, { "name": "What is Permissible Post-Nikkah and Pre-Marriage?", "link": "https://muslimmatters.org/2014/02/06/whats-matter-permissible-post-nikkah-pre-marriage/", "description": "Culture actually dictates quite a bit here" }]
            }, {
                "subheading": "Walima", "subheading_description": "(Halal, separate genders, no music) Party Time! ", "links": [{ "name": "Avoiding Wedding Debt", "link": "https://web.archive.org/web/20190114050616/http://debtfreemuslims.com/wedding-debt/", "description": "Major key to success. Major. (This is another Web Archive link that might 404)" }, { "name": "Proper Etiquettes of the Wedding Night", "link": "https://seekersguidance.org/answers/general-counsel/what-are-the-proper-etiquettes-of-the-wedding-night/", "description": "Make sure to be nice. " }, { "name": "Wedding Expenses Study", "link": "http://www.cnn.com/2014/10/13/living/wedding-expenses-study/", "description": "It turns out, the husband wasn't being cheap. He just wanted to save the marriage. What a guy" }]
            }]
        }]
    }, {
        "title": "Married Life", "description": "These sections are meant to be followed in order. Don't move on to the next point unless you've looked through all the links in a given section.", "phases": [{
            "phase": "Phase One", "description": "God be with you", "subheadings": [{
                "subheading": "Du'a", "subheading_description": "The same du'a again!? It's amazing what God can do with so few words.", "links": [{ "name": "Du'a for a Righteous Spouse and Righteous Children", "link": "http://youtube.com/watch?v=KqNfitp14vc", "description": "Next step would be to actually use the Quran for more than just a few du'a to get through major life events" }]
            }, {
                "subheading": "Intimacy", "subheading_description": "Ghusul. It's the real reason why your fantasies are unrealistic. The women understand what we're talking about.", "links": [{ "name": "Islamic Guide to Sexual Relations", "link": "http://www.muslim-library.com/dl/books/English_Islamic_Guide_To_Sexual_Relations.pdf", "description": "All your weird questions answered because they know what you've been fantasizing about" }, { "name": "Like a Garment", "link": "pdfs/Like A Garment.pdf", "description": "Helpful booklet on the “taboo” stuff. But, unfortunately, nothing's really taboo with our generation, so it's really like a booklet on common problems" }, { "name": "Dead Bedrooms", "link": "https://www.youtube.com/watch?v=MJXiOLez-n4", "description": "Interview with Karim Serageldin of Noor Psychology about struggling marriages from a lack of intimacy" }]
            }]
        }, {
            "phase": "Phase Two", "description": "Holding it Together", "subheadings": [{
                "subheading": "Cycles of a Relationship", "subheading_description": "Some ups, some downs, and a lot of flat parts where nothing really interesting happens", "links": [{ "name": "What to Expect After Marriage", "link": "https://www.youtube.com/watch?v=4A-X2tkEvx4", "description": "Less alone time" }, { "name": "I Just Got Married, Why Am I Not Happy? ", "link": "https://www.youtube.com/watch?v=mFrCg4s4IqM", "description": "Because you probably didn't go through this website before marriage" }, { "name": "Does Marriage Kill Love?", "link": "https://www.youtube.com/playlist?list=PLASZSOTiCRbewIy8RF14SIZDu9P12qxl5", "description": "No, but you will by not watching this video" }, { "name": "Cooling the Fires of Marriage: Time Management", "link": "https://web.archive.org/web/20190215040409/https://www.theidealmuslimah.com/2015/10/30/cooling-the-fires-of-marriage-part-2-the-first-fire-time-management/", "description": "Personal time is basically zero after marriage. It's worth it, but you miss it sometimes (Web Archive Link)" }]
            }, {
                "subheading": "Keep Each Other Happy", "subheading_description": "It's not that hard. You just have to sacrifice everything you've ever loved for the sake of this one person and compromise on every other habit you used to have. Just kidding! Or are we o-O", "links": [{ "name": "10 Habits of Happy Muslim Couples", "link": "http://productivemuslim.com/happy-muslim-couples/?utm_source=getresponse&utm_medium=email&utm_campaign=ProductiveMuslim+NewsLetter&utm_content=[[rssitem_title]]#utm_source=rss&utm_medium=rss&utm_campaign=happy-muslim-couples", "description": "#11: They both went through this website" }, { "name": "The 5 Love Languages: The Secret to Love That Lasts", "link": "https://read.amazon.com/kp/embed?asin=B00OICLVBI&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_xVTVzbJCK3A7B", "description": "White people been copying the Sunnah for centuries, but they just know how to make money off of it." }, { "name": "Three Components of a Happy Marriage", "link": "https://www.youtube.com/watch?v=ae3atLlhRH0", "description": "#4: They bookmark this website and share it across all their social media sites" }, { "name": "Covering the Faults of your Spouse", "link": "https://www.youtube.com/watch?v=wIYnzgieJUE", "description": "Like a garment does. Get it? It's from the ayah of the Quran!" }, { "name": "The Spouse-ship Enterprise", "link": "http://aljumuah.com/the-spouse-ship-enterprise/", "description": "The author made a Star Trek reference. This is now a mandatory read" }, { "name": "10 Ways to be the Ideal Muslim Husband", "link": "http://aljumuah.com/10-ways-to-be-the-ideal-muslim-husband/", "description": "If everyone would just fear God we wouldn't need these types of articles" }, { "name": "Emotional Intelligence Personified: How Following the Sunnah Can Save Your Marriage", "link": "https://www.almadina.org/studio/articles/emotional-intelligence-personified-how-following-the-sunnah-can-save-your-marriage", "description": "You thought IQ was important when the whole time you should have been worried about EI" }]
            }, {
                "subheading": "Conflict Resolution", "subheading_description": "Destroy your ego and this becomes super duper easy… but you probably won't do that so you'd better read all this.", "links": [{ "name": "Islam and Ego", "link": "https://youtube.com/watch?v=xtjwtmjbOKE", "description": "Leggo your Eggo" }, { "name": "Cooling the Fires of Marriage: Conflict Resolution", "link": "https://web.archive.org/web/20190610043416/https://www.theidealmuslimah.com/2015/10/30/cooling-the-fires-of-marriage-part-1-an-approach-to-conflict-resolution/", "description": "The only relationship that won't have conflict is the one you'll have in paradise. Until then, read up (Web Archive Link)" }, { "name": "Cooling the Fires of Marriage: Parents and In-Laws", "link": "https://web.archive.org/web/20190719203107/http://www.theidealmuslimah.com/2015/11/10/cooling-the-fires-of-marriage-part-3-the-second-fire-parents-and-in-laws/", "description": "They love you so much they want you for themselves. Or, at least that's the excuse we give them (Web Archive Link)" }, { "name": "7 Ways to Build Positive Relationships with In-Laws", "link": "https://www.youtube.com/watch?v=-NOQxpREPWI", "description": "If you were perfect there'd never be any issues. Why can't you be perfect!?" }, { "name": "Keys to Improve Marriage", "link": "https://www.youtube.com/playlist?list=PL7a9yN1UCJGyWq38DNNrmxLsbLSv0tY4u", "description": "“We don't talk anymore. We don't talk anymore” If you understood that reference, refer back to “Repentance” " }, { "name": "Being Tested Through Marriage", "link": "https://youtube.com/watch?v=F5_BufE0_dA", "description": "The answer sheet is in that 600 page book that you have collecting dust on your shelf." }, { "name": "Forgiveness in Marriage", "link": "https://youtube.com/watch?v=i-EP_lBJE_o", "description": "Forgive and forget. “Forget” means that you don't bring it up months later…" }, { "name": "It's Not About the Nail", "link": "https://youtube.com/watch?v=-4EDhdAHrOg", "description": "Communication in marriage summarized in two minutes" }]
            }]
        }, {
            "phase": "Phase Three", "description": "Epilogue", "subheadings": [{
                "subheading": "Children", "subheading_description": "“It's a little early to be thinking about that!” Your parents said the same thing before you accidentally happened.", "links": [{ "name": "Children Around the Prophet", "link": "https://www.youtube.com/playlist?list=PLT2-p8rVhA7zR0KsKvb73z_niOU1JXktf", "description": "It turns out, the Sunnah isn't to yell at the kids for having fun" }, { "name": "Marriage After Children", "link": "https://www.youtube.com/watch?v=OPeVgP9PCqY", "description": "For most people, this represents most of their married life. Kinda weird to think about, huh?" }, { "name": "Virtues of Adoption and Fostering", "link": "https://www.youtube.com/watch?v=u0BidbbUScc", "description": "If Allah has written that the wife can't bear children, then maybe He wants you to adopt one. A child, not a wife. This is why grammar is important." }]
            }]
        }, {
            "phase": "Phase Never", "description": "The Other Side", "subheadings": [{
                "subheading": "Highway to Hell", "subheading_description": "Too long; didn't read: Don't be a garbage human being and keep praying 5 times a day.", "links": [{ "name": "Abuse in Relationships", "link": "https://www.youtube.com/watch?v=vaEMNx7a1bY", "description": "I can't believe this is a real issue. Why are people so stupid?" }, { "name": "Why is Cheating/Adultery Wrong?", "link": "http://www.thepublicdiscourse.com/2015/09/15682/", "description": "Because just saying \"It's haram!\" doesn't cut it these days" }, { "name": "Removing the Silence on Domestic Violence ", "link": "https://youtube.com/watch?v=BDEKJDgXO-U", "description": "Like seriously, why? Why?!" }, { "name": "Abuse of Women", "link": "https://www.youtube.com/watch?v=pFvw4XvVpOA", "description": "Truth is, this entire website is actually to help women learn how to avoid bad men" }, { "name": "Islam and Violence Against Women", "link": "https://www.youtube.com/watch?v=NxOj-dVvTdw", "description": "Muslims aren't immune to this problem" }, { "name": "Hitting Women", "link": "https://www.youtube.com/watch?v=1azySjz4edk", "description": "It's sad we even have to talk about this stuff..." }, { "name": "Quran and Domestic Violence", "link": "https://youtube.com/watch?v=3wACzVQLvHM", "description": "Probably best if we understood it for when that non-Muslim eventually asks, “Why's the KOR-ANN let you hit women!?”" }]
            }, {
                "subheading": "Divorce", "subheading_description": "The whole point of this website is to help prevent this, but you need to be educated so that no one can scam you if it has to come to divorce", "links": [{ "name": "The Fiqh of Marriage and Divorce", "link": "pdfs/Fiqh of Marriage.pdf", "description": "PDF courtesy of Shaykh Mustafa Umar from California Islamic University" }, { "name": "Post Marriage Problems", "link": "https://youtube.com/watch?v=mKDm1NxQ3qs", "description": "Make du'a for all the single moms and dads out there" }, { "name": "American-Muslim Trends in Marriage and Divorce", "link": "http://aljumuah.com/marriage-and-divorce-american-muslim-trends-amira-murphy/", "description": "It doesn't have to be this way. We can change." }]
            }]
        }]
    }]
}; function getWebsite() { return website; }